function C = c(in1,in2)
%C
%    C = C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Apr-2021 19:27:07

q2 = in1(2,:);
q_dot1 = in2(1,:);
q_dot2 = in2(2,:);
t2 = sin(q2);
C = [q_dot2.^2.*t2.*(-3.0./5.0)-q_dot1.*q_dot2.*t2.*(6.0./5.0);q_dot1.^2.*t2.*(3.0./5.0)];
