function G = g(in1)
%G
%    G = G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Apr-2021 18:20:22

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = t3.*(9.81e+2./2.5e+2);
G = [t4+cos(q1).*(9.81e+2./2.5e+2);t4];
