function M = M(in1)
%M
%    M = M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-Apr-2021 11:33:28

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.*(3.0./5.0);
t4 = t3+3.4e+1./2.5e+1;
M = reshape([t2.*(6.0./5.0)+9.3e+1./2.5e+1,t4,t4,3.4e+1./2.5e+1],[2,2]);
